name: Build

on:
  - push

env:
  SKETCHES_REPORTS_PATH: sketches-reports
  SKETCHES_REPORTS_ARTIFACT_NAME: sketches-reports
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn:
          - "Heltec-esp32:esp32:wifi_lora_32_V2"
        sketch:
          - ./src/MamaDuck
          - ./src/PapaDuck
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Compile
        run: ./.ci/build.sh "${{ matrix.sketch }}" "${{ matrix.fqbn }}"
        shell: sh

      - name: Upload sketches report to workflow artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}

      - name: Upload bin
        uses: actions/upload-artifact@v3
        with:
          path: ./build/bin
          if-no-files-found: error

  report:
    needs: [compile]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Download sketches reports artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.SKETCHES_REPORTS_ARTIFACT_NAME }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}

      - uses: arduino/report-size-deltas@v1
        with:
          sketches-reports-source: ${{ env.SKETCHES_REPORTS_PATH }}
